import 'dart:convert';

class ViewFacturaModel {
  dynamic documento;
  dynamic tipoDocumento;
  dynamic serieDocumento;
  dynamic empresa;
  dynamic localizacion;
  dynamic estacionTrabajo;
  dynamic fechaReg;
  dynamic estadoDocumento;
  dynamic desTipoDocumento;
  dynamic desSerieDocumento;
  dynamic fechaHora;
  dynamic userName;
  dynamic idDocumento;
  dynamic refIdDocumento;
  dynamic refSerie;
  dynamic documentoNombre;
  dynamic documentoNit;
  dynamic feCae;
  dynamic feNumeroDocumento;
  dynamic feNumeroDte;
  dynamic felUuidAnulacion;
  dynamic fechaDocumento;
  dynamic cuentaCorrentista;
  dynamic cuentaCorrentistaRef;
  dynamic nacionalidad;
  dynamic idCuenta;
  dynamic nombre;
  dynamic idVendedor;
  dynamic vendedor;
  dynamic producto;
  dynamic unidadMedida;
  dynamic bodega;
  dynamic claseProducto;
  dynamic marca;
  dynamic productoId;
  dynamic desProducto;
  dynamic desUnidadMedida;
  dynamic desMarca;
  dynamic desBodega;
  dynamic desClaseProducto;
  dynamic exento;
  dynamic estado;
  dynamic reversion;
  dynamic cantidadAnt;
  dynamic cantidad;
  dynamic cantidadPos;
  dynamic monto;
  dynamic montoSinIva;
  dynamic iva;
  dynamic costoTotal;
  dynamic existencia;
  dynamic costoInventario;
  dynamic cantFacturada;
  dynamic tipoPago;
  dynamic tipoCargoAbono;
  dynamic deposito;
  dynamic recibos;
  dynamic saldo;

  ViewFacturaModel({
    required this.documento,
    required this.tipoDocumento,
    required this.serieDocumento,
    required this.empresa,
    required this.localizacion,
    required this.estacionTrabajo,
    required this.fechaReg,
    required this.estadoDocumento,
    required this.desTipoDocumento,
    required this.desSerieDocumento,
    required this.fechaHora,
    required this.userName,
    required this.idDocumento,
    required this.refIdDocumento,
    required this.refSerie,
    required this.documentoNombre,
    required this.documentoNit,
    required this.feCae,
    required this.feNumeroDocumento,
    required this.feNumeroDte,
    required this.felUuidAnulacion,
    required this.fechaDocumento,
    required this.cuentaCorrentista,
    required this.cuentaCorrentistaRef,
    required this.nacionalidad,
    required this.idCuenta,
    required this.nombre,
    required this.idVendedor,
    required this.vendedor,
    required this.producto,
    required this.unidadMedida,
    required this.bodega,
    required this.claseProducto,
    required this.marca,
    required this.productoId,
    required this.desProducto,
    required this.desUnidadMedida,
    required this.desMarca,
    required this.desBodega,
    required this.desClaseProducto,
    required this.exento,
    required this.estado,
    required this.reversion,
    required this.cantidadAnt,
    required this.cantidad,
    required this.cantidadPos,
    required this.monto,
    required this.montoSinIva,
    required this.iva,
    required this.costoTotal,
    required this.existencia,
    required this.costoInventario,
    required this.cantFacturada,
    required this.tipoPago,
    required this.tipoCargoAbono,
    required this.deposito,
    required this.recibos,
    required this.saldo,
  });

  factory ViewFacturaModel.fromJson(String str) =>
      ViewFacturaModel.fromMap(json.decode(str));

  String toJson() => json.encode(toMap());

  factory ViewFacturaModel.fromMap(Map<String, dynamic> json) =>
      ViewFacturaModel(
        documento: json["Documento"],
        tipoDocumento: json["Tipo_Documento"],
        serieDocumento: json["Serie_Documento"],
        empresa: json["Empresa"],
        localizacion: json["Localizacion"],
        estacionTrabajo: json["Estacion_Trabajo"],
        fechaReg: json["Fecha_Reg"],
        estadoDocumento: json["Estado_Documento"],
        desTipoDocumento: json["Des_Tipo_Documento"],
        desSerieDocumento: json["Des_Serie_Documento"],
        fechaHora: json["Fecha_Hora"],
        userName: json["UserName"],
        idDocumento: json["Id_Documento"],
        refIdDocumento: json["Ref_Id_Documento"],
        refSerie: json["Ref_Serie"],
        documentoNombre: json["Documento_Nombre"],
        documentoNit: json["Documento_NIT"],
        feCae: json["FE_CAE"],
        feNumeroDocumento: json["FE_numeroDocumento"],
        feNumeroDte: json["FE_numeroDte"],
        felUuidAnulacion: json["FEL_UUID_Anulacion"],
        fechaDocumento: json["Fecha_Documento"],
        cuentaCorrentista: json["Cuenta_Correntista"],
        cuentaCorrentistaRef: json["Cuenta_Correntista_Ref"],
        nacionalidad: json["Nacionalidad"],
        idCuenta: json["Id_Cuenta"],
        nombre: json["Nombre"],
        idVendedor: json["Id_Vendedor"],
        vendedor: json["Vendedor"],
        producto: json["producto"],
        unidadMedida: json["Unidad_Medida"],
        bodega: json["Bodega"],
        claseProducto: json["Clase_Producto"],
        marca: json["Marca"],
        productoId: json["Producto_Id"],
        desProducto: json["Des_Producto"],
        desUnidadMedida: json["Des_Unidad_Medida"],
        desMarca: json["Des_Marca"],
        desBodega: json["Des_Bodega"],
        desClaseProducto: json["Des_Clase_Producto"],
        exento: json["Exento"],
        estado: json["Estado"],
        reversion: json["Reversion"],
        cantidadAnt: json["Cantidad_Ant"],
        cantidad: json["Cantidad"],
        cantidadPos: json["Cantidad_Pos"],
        monto: json["Monto"],
        montoSinIva: json["Monto_SinIVA"],
        iva: json["IVA"],
        costoTotal: json["Costo_Total"],
        existencia: json["existencia"],
        costoInventario: json["costo_inventario"],
        cantFacturada: json["Cant_Facturada"],
        tipoPago: json["Tipo_Pago"],
        tipoCargoAbono: json["Tipo_Cargo_Abono"],
        deposito: json["Deposito"],
        recibos: json["Recibos"],
        saldo: json["Saldo"],
      );

  Map<String, dynamic> toMap() => {
        "Documento": documento,
        "Tipo_Documento": tipoDocumento,
        "Serie_Documento": serieDocumento,
        "Empresa": empresa,
        "Localizacion": localizacion,
        "Estacion_Trabajo": estacionTrabajo,
        "Fecha_Reg": fechaReg,
        "Estado_Documento": estadoDocumento,
        "Des_Tipo_Documento": desTipoDocumento,
        "Des_Serie_Documento": desSerieDocumento,
        "Fecha_Hora": fechaHora,
        "UserName": userName,
        "Id_Documento": idDocumento,
        "Ref_Id_Documento": refIdDocumento,
        "Ref_Serie": refSerie,
        "Documento_Nombre": documentoNombre,
        "Documento_NIT": documentoNit,
        "FE_CAE": feCae,
        "FE_numeroDocumento": feNumeroDocumento,
        "FE_numeroDte": feNumeroDte,
        "FEL_UUID_Anulacion": felUuidAnulacion,
        "Fecha_Documento": fechaDocumento,
        "Cuenta_Correntista": cuentaCorrentista,
        "Cuenta_Correntista_Ref": cuentaCorrentistaRef,
        "Nacionalidad": nacionalidad,
        "Id_Cuenta": idCuenta,
        "Nombre": nombre,
        "Id_Vendedor": idVendedor,
        "Vendedor": vendedor,
        "producto": producto,
        "Unidad_Medida": unidadMedida,
        "Bodega": bodega,
        "Clase_Producto": claseProducto,
        "Marca": marca,
        "Producto_Id": productoId,
        "Des_Producto": desProducto,
        "Des_Unidad_Medida": desUnidadMedida,
        "Des_Marca": desMarca,
        "Des_Bodega": desBodega,
        "Des_Clase_Producto": desClaseProducto,
        "Exento": exento,
        "Estado": estado,
        "Reversion": reversion,
        "Cantidad_Ant": cantidadAnt,
        "Cantidad": cantidad,
        "Cantidad_Pos": cantidadPos,
        "Monto": monto,
        "Monto_SinIVA": montoSinIva,
        "IVA": iva,
        "Costo_Total": costoTotal,
        "existencia": existencia,
        "costo_inventario": costoInventario,
        "Cant_Facturada": cantFacturada,
        "Tipo_Pago": tipoPago,
        "Tipo_Cargo_Abono": tipoCargoAbono,
        "Deposito": deposito,
        "Recibos": recibos,
        "Saldo": saldo,
      };
}
